name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build for ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        sdk:
          - snapshot
          - openwrt-18.06
        include:
          - arch: arc_archs
            sdk: openwrt-18.06
          - arch: powerpc_8540
            sdk: openwrt-18.06
        exclude:
          - arch: powerpc_8548
            sdk: openwrt-18.06
          # https://github.com/openwrt/packages/issues/19511
          - arch: mipsel_24kc_24kf
            sdk: snapshot

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Retrieve Version
        id: ver
        run: |
          { read luci_ver; read pkgs_ver; read passwall2_ver; } < current_version
          echo "luci=$luci_ver" >> $GITHUB_OUTPUT
          echo "pkgs=$pkgs_ver" >> $GITHUB_OUTPUT
          echo "passwall2=$passwall2_ver" >> $GITHUB_OUTPUT

      - name: Build Package
        uses: openwrt/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          EXTRA_FEEDS: >-
            src-git|passwall_packages|https://github.com/xiaorouji/openwrt-passwall^${{ steps.ver.outputs.pkgs }}
            src-git|passwall_luci|https://github.com/xiaorouji/openwrt-passwall^${{ steps.ver.outputs.luci }}
            src-git|passwall2|https://github.com/xiaorouji/openwrt-passwall2^${{ steps.ver.outputs.passwall2 }}
          KEY_BUILD: ${{ secrets.SIGN_PRIV_KEY }}
          V: s

      - name: Tar Output Folder
        run: |
          sdk=${{ matrix.sdk }}
          if [[ $sdk == *"openwrt"* ]]; then
            # openwrt-18.06 -> releases/packages-18.06
            abi=${sdk/openwrt/releases\/packages}
          else
            # snapshot -> snapshots/packages
            abi=snapshots/packages
          fi
          DIST_DIR=$PWD/dist/$abi
          mkdir -p $DIST_DIR

          pushd bin/packages
          cp -r --parents */passwall* $DIST_DIR
          popd

          tar -cf dist.tar dist

      - name: Upload Output Folder
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-passwall-${{ matrix.arch }}-${{ matrix.sdk }}
          path: dist.tar
          retention-days: 7

  deploy:
    concurrency:
      group: deploy_osdn
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch All Builds
        uses: actions/download-artifact@v3
        with:
          path: all-builds

      - name: Merge All Builds
        run: |
          mkdir dist
          for d in all-builds/*; do
            tar -xf $d/dist.tar -C $d
            rsync -a $d/dist/ dist
          done
          cp passwall.pub dist

      - name: Deploy
        uses: Burnett01/rsync-deployments@5.2.1
        with:
          switches: -avz --delete --exclude-from=archived.txt
          path: dist/
          remote_path: /root/openwrt_passwall/openwrt-passwall-build/
          remote_host: hk.vm.cloudteam.top
          remote_user: ${{ secrets.HK_DEPLOY_USER }}
          remote_key_pass: ${{ secrets.HK_DEPLOY_KEY_PASS }}
