name: Scan openwrt-passwall Version

on:
  schedule:
    - cron: "0 19 * * *" # every day at UTC+8 3:00AM
  workflow_dispatch:

jobs:
  check:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Checkout Upstream Luci
        uses: actions/checkout@v3
        with:
          repository: xiaorouji/openwrt-passwall
          ref: luci
          path: passwall_luci

      - name: Checkout Upstream Packages
        uses: actions/checkout@v3
        with:
          repository: xiaorouji/openwrt-passwall
          ref: packages
          path: passwall_packages

      - name: Checkout Passwall2
        uses: actions/checkout@v3
        with:
          repository: xiaorouji/openwrt-passwall2
          path: passwall2

      - name: Compare Version
        id: compare_version
        run: |
          printf -v upstream_version "%s\n%s\n%s" \
            "$(git -C passwall_luci rev-parse HEAD)" \
            "$(git -C passwall_packages rev-parse HEAD)" \
            "$(git -C passwall2 rev-parse HEAD)"

          cmp -s <(echo "$upstream_version") current_version ||
            echo "version=${upstream_version//$'\n'/ }" >> $GITHUB_OUTPUT

      - name: Commit New Version
        if: steps.compare_version.outputs.version != ''
        run: |
          version="${{ steps.compare_version.outputs.version }}"
          echo -e "${version// /\\n}" > current_version
          git add current_version

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          read -r luci_ver pkgs_ver passwall2_ver <<< $version
          tag_name="${luci_ver:0:7}-${pkgs_ver:0:7}-${passwall2_ver:0:7}"

          git commit -F- << EOF
          chore: bump to ${tag_name}

          luci: xiaorouji/openwrt-passwall@${luci_ver}
          packages: xiaorouji/openwrt-passwall@${pkgs_ver}
          passwall2: xiaorouji/openwrt-passwall2@${passwall2_ver}
          EOF
          git push

          git tag -a "$tag_name" -m "$tag_name"
          git push origin "$tag_name"
